version: "3.6"
services:
  gamestore-java-spring-api:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: gamestore-java-spring-api
    ports:
      - "8021:8080"
    volumes:
      - "../:/app"
      # Linux
      - "${HOME}/.m2:/root/.m2"
      # Windows
      # - "D:\\Development\\.m2:/root/.m2"
      - "//var/run/docker.sock:/var/run/docker.sock"
    working_dir: /app
    stdin_open: true
    tty: true
    mem_limit: 2g
    mem_reservation: 2g
    cpus: 0.5
networks:
  default:
    external: true
    name: hustletech
